- name: varaibles from task level
  hosts: web
  tasks:
    - name: variables from task level
      vars:
        course: "devops with aws"
        ansible.builtin.debug:
          msg: "hi i am learing {{course}}"