- name: variables from promt
  hosts: web
  vars_promt:
  - name: course
    promt: enter the course name
  - name: duration
    promt: enter the duration
  tasks:
  - name: varsiables from promt
    ansible.biultin.debug:
      msg: "hi i am learing {{course}},with duration {{duration}}"