- name: variables from promt
  hosts: web
  vars_prompt:
  - name: course
    prompt: enter the course name
  - name: duration
    prompt: enter the duration
  tasks:
  - name: variables from promt
    ansible.builtin.debug:
      msg: "hi i am learing {{course}},with duration {{duration}}