- name: to check the given number is less or greater 
  hosts: local
  connection: local
  vars_prompt:
  - name: my_number
    prompt: please enter the number
    private: true
  tasks:
  - name: print this is number is less then less
    ansible.builtin.debug:
      msg: "given number {{ my_number }} is less then 10"
    when: my_number | int < 10

  - name: print this number is greater then 10
    ansible.builtin.debug:
      msg: "given number is greater then 10"
    when: my_number | int > 10  