- name: create user
  hosts: web
  become: yes
  tasks:
  - name: check user is exist or not
    ansible.builtin.command: id expense
    rigister: USER
    ignore_errors: True

  - name: print the user info
    ansible.builtin.command:
      msg: "user info :: {{ USER }}"

  - name: create user if not exist
    ansible.builtin.command: useradd expense
    when: USER.rc != 0