- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: "subnet-01201808a891273e0"
    sg_id: "sg-070103aea9684415b"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
      - mysql
      - backend
      - frontend
  tasks:
  - name: "creating ec2 instances"
    ansible.builtin.ec_instance:
    name: "{{ item }}"
    vpc_subnet_id: "{{ subnet_id }}"
    instance_type: t3.micro
    security_group: "{{ sg_id }}"
    image_id: "{{ ami_id }}"
  loop: "{{ instances }}"
  register: ec2-instances
